menu:
  Home: /
  Archives: /archives

widgets: 
- search
- category
- tag
- other

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: